### ISSUE TITLE
[Request] Level Sort & Search

### ISSUE THREAD

**Issue by ghost** [HJfod/gdshare-legacy-app#10]
Currently, all levels are listed without any way to sort or search through them. Makes it pretty difficult to find a specific level.

**Comment by HJfod** [comment]
![image](https://user-images.githubusercontent.com/60038575/106708512-e8f42880-65ea-11eb-8bc4-4fee6822631b.png)
Does the search button below the level list not work?

**Comment by ghost** [comment]
Your entire menu interface looks much better than mine, am I somehow using an old version? I swear I downloaded the latest release...

There is no search bar in my version.

**Comment by ghost** [comment]
Oh my god, I'm stupid. I meant to post this issue in GDTools, not GDShare.
